<h1>holas</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>NOMBRE</th>
      <th>CORREO</th>
    </tr>
  </thead>
  <tbody>
    @foreach($users as $user)
    <tr>
      <td>{{$user->id}}</td>
      <td>{{$user->name}}</td>
      <td>{{$user->email}}</td>
    </tr>
    @endforeach
  </tbody>
</table>
